version: "2.1"
services:
  # Elastic Search
  elasticsearch:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: elasticsearch
  redis:
    hostname: redis
    image: redis:3.2.11
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=magento
      - RABBITMQ_DEFAULT_PASS=magento
