#!/usr/bin/env bash

## manage redis
##
## Usage: fin redis

# Abort if anything fails
set -e

# Enable container and settings
redis_enable ()
{
  echo "  Enabling redis ..."
  fin magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=0 
  fin magento setup:config:set --page-cache=redis --page-cache-redis-server=redis --page-cache-redis-db=1 
  fin magento setup:config:set --session-save=redis --session-save-redis-host=redis --session-save-redis-log-level=3 --session-save-redis-db=2 
}

# Disable container and settings
redis_disable ()
{
	echo " Not yet ready. Running checks..."
	# Make sure cli container is running
	if ! (fin ps | grep "_cli_" | grep "Up" >/dev/null); then
		echo "  ERROR: Start the project with fin start first" && exit 1
	fi
    fin magento setup:config:set --cache-backend=files
    fin magento setup:config:set --page-cache=files
    fin magento setup:config:set --session-save=files
}

#------------------------------------------ Runtime -----------------------------------------------

cd "$PROJECT_ROOT"

case "$1" in
	enable)
		redis_enable
		;;
	disable)
		redis_disable
		;;
	*)
		echo "Usage: fin redis <enable|disable>"
		exit 1
		;;
esac
